### ISSUE TITLE
confusion using with multilevel

### ISSUE THREAD

**Issue by daywiss** [juliangruber/level-sec#1]
it seems in your multi level example you expose each 'Index' as a distinct database to the client.  Is this how it has to be done? or is there a way to access each one from the original db object when opened with a manifest on the client?  I dont explicitly add anything to the manifest before I save it. 

I've been able to access my sublevels from a single client connection over multilevel, and they even  have a 'byWhatever' function, but I dont understand how to use it. It basically fails saying the function has no method 'get'.

i can provide some code if this doesnt make sense...

**Comment by juliangruber** [comment]
You have to add the indexed db object to the manifest manually. I'll add this to the docs.

``` js
var index = require('level-sec');
var createManifest = require('level-manifest');

db.methods = {};
db.posts = index(db.sublevel('posts'))
  .by('Slug', ['slug'])
  .db;
db.methods.posts = {
  type: 'object',
  methods: createManifest(db.posts).methods 
};
```

**Comment by daywiss** [comment]
thanks for the prompt reply. I spent some time trying to get this to work in my own code and couldnt. so i went to your test program and updated it. that seemed to work after some tweaking, though im not sure how to get the manifest file in a consistent place for client and server. heres the code, maybe you could check to make sure this is right and update your example:

```
var MemDB = require('memdb');
var Index = require('..');
var sub = require('level-sublevel');
var test = require('tape');
var multilevel = require('multilevel');
var createManifest = require('level-manifest')

test('multilevel', function(t) {
  t.plan(7);

  var db = sub(MemDB({ valueEncoding: 'json' }));

  db.posts = Index(db.sublevel('posts'))
    .by('Title', 'title')
    .by('Length', ['body.length'])
    .by('Author', ['author', 'title'])
    .db;

  db.methods = db.methods || {};

  db.methods.posts = {
    type: 'object',
    methods: createManifest(db.posts).methods 
  };

  multilevel.writeManifest(db, './manifest.json');

  var server = multilevel.server(db);
  var client = multilevel.client(require('../manifest.json'));

  server.pipe(client.createRpcStream()).pipe(server);

  var post = {
    title: 'a title',
    body: 'lorem ipsum',
    author: 'julian'
  };

  client.posts.put('1337', post, function(err) {
    t.error(err);

    client.posts.byTitle.get('a title', onPost);
    client.posts.byLength.get('11', onPost);
    client.posts.byAuthor.get('julian!a title', onPost);

    function onPost(err, _post) {
      t.error(err);
      t.deepEqual(_post, post);
    }
  });
});
```

**Comment by juliangruber** [comment]
I added a test for this. I'm not sure what you did wrong, maybe the relative `package.json` paths screwed you?

To get client and server to use the same manifest is out of scope for multilevel. What I generally do is write the manifest whenever my db server starts and then copy it to a client reachable location.

**Comment by daywiss** [comment]
i had some out of date dependency somewherre in my project. i eventually wiped my node modules folder and got the latest version of everything and things started working. took me forever to figure that one out.
